CREATE DATABASE IF NOT EXISTS epam;
USE epam;
CREATE TABLE IF NOT EXISTS users(id INT(4), name VARCHAR (255) PRIMARY KEY NOT NULL passwordHash VARCHAR(255), bank INT(4), authorityLvl INT(4));
CREATE TABLE IF NOT EXISTS races (id INT(4) PRIMARY KEY NOT NULL, race_date VARCHAR(32), status INT(1), horses_names VARCHAR(255), winner VARCHAR(32));
CREATE TABLE IF NOT EXISTS horses (id INT(4), name VARCHAR(32) PRIMARY KEY NOT NULL, winsCounter INT(4));
CREATE TABLE IF NOT EXISTS bets (id INT(4) PRIMARY KEY NOT NULL, amount FLOAT , race_id INT(4), horse_name VARCHAR(32), user_name VARCHAR(255));